### ISSUE TITLE
Something wrong with close_can_channel()

### ISSUE THREAD

**Issue by Nightsuki** [fishpepper/pyUSBtin#1]
Thanks for writing this project. But when i using this API, i found out there something wrong with close_can_channel function, it trapped into a deadloop and never get channel closed.

**Comment by fishpepper** [comment]
please test the latest code, this should work now (commit b67e042)

**Comment by Nightsuki** [comment]
Ya, now it's working, Thanks mate!

**Comment by Nightsuki** [comment]
BTW in `usbtin.py` line 259, it should be 0.001 second not 1 second

**Comment by fishpepper** [comment]
thanks! fixed.
